######### 开启 Spring Boot 的Bean 组件重写机制
spring:
  main:
    allow-bean-definition-overriding: true
######### Eureka Client 连接 Eureka server 地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/